### ISSUE TITLE
File Input Shrinks on Change

### ISSUE THREAD

**Issue by yankidank** [jquery-ui-bootstrap/jquery-ui-bootstrap#76] opened 2012-06-13 13:13 UTC
When you select a file for the File Input function, then change the selected object, the width of the input field will shrink in width. If you keep changing the selected item, it will continue losing width.

**Comment by panosru** [comment] 2012-06-13 13:20
@yankidank Hi! This is a duplicate of solved issue #53, take a look there.

**Closed as completed by panosru** 2012-06-13 13:20 UTC
