### ISSUE TITLE
Datepicker is not fully themed in IE9

### ISSUE THREAD

**Issue by shahnawazk** [jquery-ui-bootstrap/jquery-ui-bootstrap#17] opened 2012-01-02 11:45 UTC
I'm using IE9 and when I open up the index.html page of jquery-ui-bootstrap the theme is not fully loaded for jQuery datepicker, also the drag/re-size of dialog are a bit laggy.

**Comment by addyosmani** [comment] 2012-01-02 11:50
@shahnawazk I've noticed a little bit of lag when waiting for the preview page to load (even locally) and I think it may be related to the issue you're experiencing. My gut instinct is that the third party widgets on the page are what are to blame.

Are you able to see any theming on the datepicker in IE9 on subsequent refreshes?

For future releases what we may do is move the third party widgets into their own separate page but I want to narrow down the cause of the issue you're experiencing.

**Comment by shahnawazk** [comment] 2012-01-02 11:56
Ok, I'll try to include only jQuery ui widgets.

 Yes, I'm able to see basic theming, but the hover effect [blue] is missing that makes the Datepicker more awesome.

Thanks!

**Comment by addyosmani** [comment] 2012-01-02 12:05
@shahnawazk I'll leave this open until I can confirm, but if the hover effect is missing in IE9 that shouldn't take too long to fix. Thanks for reporting!

**Comment by shahnawazk** [comment] 2012-01-02 12:14
Ok, I'll get it in the next release. thanks!

**Comment by addyosmani** [comment] 2012-01-03 15:20
This has been fixed by some recent commits. Closing.

**Closed as completed by addyosmani** 2012-01-03 15:20 UTC
