### ISSUE TITLE
Bug on rendering tab widget

### ISSUE THREAD

**Issue by henyana** [jquery-ui-bootstrap/jquery-ui-bootstrap#142] opened 2013-01-30 01:03 UTC
Hi,

I've just downloaded stable-v.05-pre. I find that the tab widget is not correctly rendered, there is always border bottom on the active tab.

Can you fix this?
thanks.

regards,
hendra

**Comment by gtraxx** [comment] 2013-01-30 07:30
Hi, the problem is fixed in version dev (fixed in https://github.com/addyosmani/jquery-ui-bootstrap/commit/7798159130210f31c97e0ee4b86192ddc3ddc3f6)

**Comment by henyana** [comment] 2013-01-30 14:25
Hi gtraxx, 
Thanks for the answer, but it should be updated to the link download both pre and dev also?
The correct version is on this github download link.

**Comment by gtraxx** [comment] 2013-01-30 14:47
Download dev version :)

https://github.com/addyosmani/jquery-ui-bootstrap/archive/gh-pages.zip

**Closed as completed** 2013-01-31 13:17 UTC
